-- Update event command response format: remove {user}, show event name + player count
UPDATE chat_commands SET response = 'A Colossal Problem event on this server, player count [Server Count]/24.'   WHERE trigger = '/acp';
UPDATE chat_commands SET response = 'Beasts of Burden event on this server, player count [Server Count]/24.'    WHERE trigger = '/bob';
UPDATE chat_commands SET response = 'Campfire Tales event on this server, player count [Server Count]/24.'      WHERE trigger = '/ct';
UPDATE chat_commands SET response = 'Dropped Connections event on this server, player count [Server Count]/24.' WHERE trigger = '/dc';
UPDATE chat_commands SET response = 'Distinguished Guests event on this server, player count [Server Count]/24.'WHERE trigger = '/dg';
UPDATE chat_commands SET response = 'Dangerous Pastimes event on this server, player count [Server Count]/24.'  WHERE trigger = '/dpt';
UPDATE chat_commands SET response = 'Eviction Notice event on this server, player count [Server Count]/24.'     WHERE trigger = '/en';
UPDATE chat_commands SET response = 'Encryptid event on this server, player count [Server Count]/24.'           WHERE trigger = '/enc';
UPDATE chat_commands SET response = 'Free Range event on this server, player count [Server Count]/24.'          WHERE trigger = '/fr';
UPDATE chat_commands SET response = 'Feed the People event on this server, player count [Server Count]/24.'     WHERE trigger = '/ftp';
UPDATE chat_commands SET response = 'Guided Meditation event on this server, player count [Server Count]/24.'   WHERE trigger = '/gm';
UPDATE chat_commands SET response = 'Heart of the Swamp event on this server, player count [Server Count]/24.'  WHERE trigger = '/hots';
UPDATE chat_commands SET response = 'Jailbreak event on this server, player count [Server Count]/24.'           WHERE trigger = '/jb';
UPDATE chat_commands SET response = 'Lode Baring event on this server, player count [Server Count]/24.'         WHERE trigger = '/lb';
UPDATE chat_commands SET response = 'Line in the Sand event on this server, player count [Server Count]/24.'    WHERE trigger = '/lits';
UPDATE chat_commands SET response = 'Moonshine Jamboree event on this server, player count [Server Count]/24.'  WHERE trigger = '/mj';
UPDATE chat_commands SET response = 'Most Wanted event on this server, player count [Server Count]/24.'         WHERE trigger = '/mw';
UPDATE chat_commands SET response = 'Neurological Warfare event on this server, player count [Server Count]/24.'WHERE trigger = '/nw';
UPDATE chat_commands SET response = 'One Violent Night event on this server, player count [Server Count]/24.'   WHERE trigger = '/ovn';
UPDATE chat_commands SET response = 'Project Paradise event on this server, player count [Server Count]/24.'    WHERE trigger = '/pp';
UPDATE chat_commands SET response = 'The Path to Enlightenment event on this server, player count [Server Count]/24.' WHERE trigger = '/pte';
UPDATE chat_commands SET response = 'Radiation Rumble event on this server, player count [Server Count]/24.'    WHERE trigger = '/rr';
UPDATE chat_commands SET response = 'Riding Shotgun event on this server, player count [Server Count]/24.'      WHERE trigger = '/rs';
UPDATE chat_commands SET response = 'Seismic Activity event on this server, player count [Server Count]/24.'    WHERE trigger = '/sa';
UPDATE chat_commands SET response = 'Safe and Sound event on this server, player count [Server Count]/24.'      WHERE trigger = '/sas';
UPDATE chat_commands SET response = 'Scorched Earth event on this server, player count [Server Count]/24.'      WHERE trigger = '/sbq';
UPDATE chat_commands SET response = 'Surface to Air event on this server, player count [Server Count]/24.'      WHERE trigger = '/sos';
UPDATE chat_commands SET response = 'Tunnel of Love event on this server, player count [Server Count]/24.'      WHERE trigger = '/tol';
UPDATE chat_commands SET response = 'Tea Time event on this server, player count [Server Count]/24.'            WHERE trigger = '/tt';
UPDATE chat_commands SET response = 'Test Your Metal event on this server, player count [Server Count]/24.'     WHERE trigger = '/tym';
UPDATE chat_commands SET response = 'Uranium Fever event on this server, player count [Server Count]/24.'       WHERE trigger = '/uf';
