/**
 * The cosmetics catalog — colours and effects, with their tier gates.
 *
 * This module is the SINGLE SOURCE OF TRUTH. It is served over
 * GET /api/cosmetics/catalog and consumed by the web Profile panel, the Discord
 * `/cosmetics` autocomplete, and the validator — nothing re-declares the list.
 *
 * Every colour here is machine-verified by cosmeticsCatalog.test.ts against two gates:
 *   - contrast: worst-case WCAG ratio >= MIN_CONTRAST across every surface a name
 *     renders on (see utils/colorContrast.ts)
 *   - reserved: far enough from every role / theme / channel colour that it cannot be
 *     used to impersonate staff or imitate system chrome (see reservedColors.ts)
 * A bad preset therefore fails CI rather than shipping and being discovered in chat.
 *
 * The palette was generated by farthest-point selection over HSL space subject to both
 * gates, so the colours are maximally distinguishable from each other in the picker
 * rather than hand-picked and accidentally similar.
 */
import { SupporterTier } from '../../utils/supporterTier';

export interface ColorPreset {
  id: string;
  label: string;
  hex: string;
  /** Minimum tier required. 'none' = available to everyone. */
  tier: SupporterTier;
}

export interface EffectPreset {
  id: string;
  label: string;
  tier: SupporterTier;
  /** Short user-facing explanation, reused verbatim by the web UI and Discord. */
  description: string;
  /**
   * Whether the effect renders in the in-game HUD.
   *
   * ALWAYS false for effects, and this is permanent, not a TODO. Scaleform crashes
   * the game outright on any `.filters` assignment (FCMChatWidget.hx crash rule #1,
   * "violations crashed the game in production") and `StyleSheet` is banned too, so
   * glow, gradient and animation cannot exist in-game at any point in the future.
   * Solid colours and text prefixes are the entire in-game surface.
   *
   * Surfaced through the API so the UI can label effects honestly rather than selling
   * someone a cosmetic that silently does nothing where they play.
   */
  inGameSupported: false;
  /** True when the effect animates — drives the reduced-motion / opt-out collapse. */
  animated: boolean;
}

// ── Colours ───────────────────────────────────────────────────────────────────

/** Free tier: muted, tasteful, readable. Available to every user forever. */
export const FREE_COLORS: readonly ColorPreset[] = [
  { id: 'rose-quartz',   label: 'Rose Quartz',   hex: '#EDABAB', tier: 'none' },
  { id: 'wasteland-wheat', label: 'Wasteland Wheat', hex: '#EAEA9A', tier: 'none' },
  { id: 'sage',          label: 'Sage',          hex: '#B8CF81', tier: 'none' },
  { id: 'mutagen',       label: 'Mutagen',       hex: '#8CDB57', tier: 'none' },
  { id: 'stimpak',       label: 'Stimpak',       hex: '#ABEDB5', tier: 'none' },
  { id: 'seafoam',       label: 'Seafoam',       hex: '#7EC8AE', tier: 'none' },
  { id: 'cryo',          label: 'Cryo',          hex: '#57DBDB', tier: 'none' },
  { id: 'frost',         label: 'Frost',         hex: '#ABBFED', tier: 'none' },
  { id: 'dusk',          label: 'Dusk',          hex: '#868DCB', tier: 'none' },
  { id: 'orchid',        label: 'Orchid',        hex: '#EBA2EB', tier: 'none' },
  { id: 'magenta-dust',  label: 'Magenta Dust',  hex: '#DF68C7', tier: 'none' },
  { id: 'dusty-rose',    label: 'Dusty Rose',    hex: '#C87E98', tier: 'none' },
] as const;

/**
 * Supporter tier: vivid, high-saturation versions of the same hue space. The upsell is
 * "the colour that pops", which is legible at a glance next to the free palette.
 *
 * There are 11, not 12, on purpose: the vivid-violet band (hue ~245-285) has no colour
 * that clears the contrast floor while staying clear of the reserved Discord tag purple
 * (#B57AFF). Shipping a near-miss violet would either be hard to read or look like
 * channel chrome, so the slot is simply left out.
 */
export const SUPPORTER_COLORS: readonly ColorPreset[] = [
  { id: 'solar-flare',    label: 'Solar Flare',    hex: '#FE8B8B', tier: 'supporter' },
  { id: 'rad-orange',     label: 'Rad Orange',     hex: '#FD5F1C', tier: 'supporter' },
  { id: 'atomic-yellow',  label: 'Atomic Yellow',  hex: '#F8FE8B', tier: 'supporter' },
  { id: 'toxic-lime',     label: 'Toxic Lime',     hex: '#C4FD1C', tier: 'supporter' },
  { id: 'mutagen-burst',  label: 'Mutagen Burst',  hex: '#70F835', tier: 'supporter' },
  { id: 'plasma-green',   label: 'Plasma Green',   hex: '#81FE87', tier: 'supporter' },
  { id: 'aqua-flare',     label: 'Aqua Flare',     hex: '#1CFDAE', tier: 'supporter' },
  { id: 'plasma-cyan',    label: 'Plasma Cyan',    hex: '#58FDFD', tier: 'supporter' },
  { id: 'quantum-blue',   label: 'Quantum Blue',   hex: '#7EA8F7', tier: 'supporter' },
  { id: 'fusion-magenta', label: 'Fusion Magenta', hex: '#FD1CFD', tier: 'supporter' },
  { id: 'hot-circuit',    label: 'Hot Circuit',    hex: '#FD4DA6', tier: 'supporter' },
] as const;

export const COLOR_PRESETS: readonly ColorPreset[] = [...FREE_COLORS, ...SUPPORTER_COLORS];

// ── Effects ───────────────────────────────────────────────────────────────────

/**
 * Rendered as pure CSS via `.fcm-name-fx--<id>` classes reading the per-user
 * `--fcm-name-color` custom property. Deliberately NOT JS-driven animation: the chat
 * feed is virtualized and memoized, and the overlay runs transparently on top of
 * Fallout 76, where every frame of JS animation work is taken from the game.
 */
export const EFFECT_PRESETS: readonly EffectPreset[] = [
  {
    id: 'none', label: 'None', tier: 'none',
    description: 'No effect — just your colour.',
    inGameSupported: false, animated: false,
  },
  // ── Supporter: readability-first. No continuous motion; Chroma Split has a
  // brief, infrequent desktop burst while remaining a supporter entitlement. ──
  {
    id: 'glow-soft', label: 'Soft Glow', tier: 'supporter',
    description: 'A gentle halo in your colour.',
    inGameSupported: false, animated: false,
  },
  {
    id: 'glow-hard', label: 'Hard Glow', tier: 'supporter',
    description: 'A tight, bright halo — reads like backlit terminal text.',
    inGameSupported: false, animated: false,
  },
  {
    id: 'outline-heavy', label: 'Heavy Outline', tier: 'supporter',
    description: 'A bold face with a thick dark outline. The most readable option over busy scenes.',
    inGameSupported: false, animated: false,
  },
  {
    id: 'chroma-split', label: 'Chroma Split', tier: 'supporter',
    description: 'A dim red/cyan fringe with a brief, occasional offset burst.',
    inGameSupported: false, animated: false,
  },
  // ── Overseer: animated. Collapse to a static sibling under reduced motion. ──
  {
    id: 'glow-pulse', label: 'Pulse Glow', tier: 'overseer',
    description: 'A halo that slowly breathes in and out.',
    inGameSupported: false, animated: true,
  },
  {
    id: 'crt-phosphor', label: 'CRT Phosphor', tier: 'overseer',
    description: 'Chroma fringing, scanlines, and a slow phosphor flicker.',
    inGameSupported: false, animated: true,
  },
  {
    id: 'glitch', label: 'Glitch', tier: 'overseer',
    description: 'Your name tears and re-assembles in an occasional burst on a varied cadence.',
    inGameSupported: false, animated: true,
  },
  {
    id: 'shimmer', label: 'Shimmer', tier: 'overseer',
    description: 'A highlight sweeps across your name.',
    inGameSupported: false, animated: true,
  },
] as const;

/**
 * Static effect each animated effect collapses to under `prefers-reduced-motion` or the
 * viewer opt-out. Kept here rather than only in CSS so the API can describe the
 * fallback and the UI can preview it honestly.
 */
export const REDUCED_MOTION_FALLBACK: Readonly<Record<string, string>> = {
  'glow-pulse': 'glow-soft',
  'crt-phosphor': 'chroma-split',
  glitch: 'chroma-split',
  shimmer: 'glow-soft',
} as const;

// ── Lookups ───────────────────────────────────────────────────────────────────

const COLOR_BY_ID = new Map(COLOR_PRESETS.map((c) => [c.id, c]));
const EFFECT_BY_ID = new Map(EFFECT_PRESETS.map((e) => [e.id, e]));

export function findColorPreset(id: string | null | undefined): ColorPreset | null {
  return id ? COLOR_BY_ID.get(id) ?? null : null;
}

export function findEffectPreset(id: string | null | undefined): EffectPreset | null {
  return id ? EFFECT_BY_ID.get(id) ?? null : null;
}

/**
 * Bounds for the free-form HSL picker.
 *
 * `minLightness` here is only the ABSOLUTE floor of the slider. The real per-hue floor
 * is computed live by `minLightnessForHue()` — luminance weights the channels very
 * unevenly, so saturated blue needs ~76% lightness to be legible while red and green
 * clear the bar far lower, and a single flat floor would either wash out every hue or
 * let blue through illegibly. The picker clamps per-hue as the user drags; the
 * validator then re-checks the exact resulting colour server-side regardless.
 */
export const CUSTOM_COLOR_BOUNDS = {
  minLightness: 40,
  maxLightness: 92,
  minSaturation: 25,
  maxSaturation: 100,
} as const;

export default {
  FREE_COLORS,
  SUPPORTER_COLORS,
  COLOR_PRESETS,
  EFFECT_PRESETS,
  REDUCED_MOTION_FALLBACK,
  CUSTOM_COLOR_BOUNDS,
  findColorPreset,
  findEffectPreset,
};
module.exports = {
  FREE_COLORS,
  SUPPORTER_COLORS,
  COLOR_PRESETS,
  EFFECT_PRESETS,
  REDUCED_MOTION_FALLBACK,
  CUSTOM_COLOR_BOUNDS,
  findColorPreset,
  findEffectPreset,
};
module.exports.default = module.exports;
