#!/usr/bin/env python3
"""Generate the offline HUD emoji catalog/embedded bitmap factories (no network)."""
import json
import hashlib
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent
def emit(name, content):
    path = ROOT.parent / name
    if "--check" in sys.argv:
        if path.read_text() != content:
            raise ValueError("Regenerate stale emoji source: " + name)
    else:
        path.write_text(content)

files = sorted((ROOT / 'images').glob('*.png'))
expected = json.loads((ROOT / 'asset-hashes.json').read_text())
actual = {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in files}
if expected != actual:
    raise ValueError("Emoji assets do not match the reviewed hash manifest")
indices = {p.stem: i for i, p in enumerate(files)}
entries = {}
commands = {}
selector_aliases = {key.replace("-fe0f", ""): key for key in indices}
for line in (ROOT / 'emoji-test.txt').read_text().splitlines():
    if not line or line.startswith('#') or ';' not in line:
        continue
    code, description = line.split(';', 1)
    points = [int(c, 16) for c in code.split()]
    key = '-'.join(f'{c:x}' for c in points if c != 0xfe0f or 0x200d in points)
    if key not in indices:
        key = selector_aliases.get(key.replace("-fe0f", ""), key)
    if key not in indices:
        raise ValueError("No bundled image for Unicode emoji: " + line)
    sequence = ''.join(chr(c) for c in points)
    name = description.split('#', 1)[1].strip().split(' ', 2)[-1]
    entries[sequence] = (indices[key], name)
    if "; fully-qualified" in line:
        commands[name] = sequence
for row in json.loads((ROOT / 'discord.json').read_text()):
    entries['discord:' + row['id']] = (indices['discord-' + row['id']], row['name'])
    commands['discord:' + row['name']] = '<' + ('a' if row.get('animated') else '') + ':' + row['name'] + ':' + row['id'] + '>'
# Keep a readable catalog; the generator embeds it as a constant, avoiding runtime JSON.
catalog = '\n'.join(f'{k}\t{v[0]}\t{v[1]}' for k,v in sorted(entries.items()))
out = ['// Generated by emoji/generate.py; do not edit.', 'class FcmEmojiCatalog {',
       '    public static function data():String { return ' + json.dumps(catalog,ensure_ascii=False) + '; }', '    public static function commands():String { return ' + json.dumps('\n'.join(k + '\t' + v for k,v in sorted(commands.items())), ensure_ascii=False) + '; }', '}', '']
emit('FcmEmojiCatalog.hx', '\n'.join(out))
out = ['// Generated by emoji/generate.py; bitmaps are instantiated only when displayed.',
       'import flash.display.BitmapData;', 'class FcmEmojiAssets {',
       '    public static function get(id:Int):BitmapData {', '        return switch (Std.int(id / 100)) {']
for group in range((len(files)+99)//100):
    out.append(f'            case {group}: group{group}(id);')
out += ['            default: null;', '        };', '    }']
for group in range((len(files)+99)//100):
    out += [f'    static function group{group}(id:Int):BitmapData {{', '        return switch (id) {']
    for i in range(group*100,min(len(files),(group+1)*100)):
        out.append(f'            case {i}: new FcmEmojiImage{i}(0, 0);')
    out += ['            default: null;', '        };', '    }']
out += ['}']
for i,p in enumerate(files):
    out.append(f'@:bitmap("emoji/images/{p.name}") class FcmEmojiImage{i} extends BitmapData {{}}')
emit('FcmEmojiAssets.hx', '\n'.join(out)+'\n')
print(f'Generated {len(entries)} emoji sequences and {len(files)} bitmaps')
